{"time":"2025-02-27T21:07:06.7556757Z","level":"INFO","msg":"stream: starting","core version":"0.19.7","symlink path":"C:\\Users\\msocz\\workbench\\oliveai\\trend-evalute\\wandb\\run-20250227_210706-40127l2p\\logs\\debug-core.log"}
{"time":"2025-02-27T21:07:06.8620162Z","level":"INFO","msg":"created new stream","id":"40127l2p"}
{"time":"2025-02-27T21:07:06.8620162Z","level":"INFO","msg":"stream: started","id":"40127l2p"}
{"time":"2025-02-27T21:07:06.8620162Z","level":"INFO","msg":"writer: Do: started","stream_id":"40127l2p"}
{"time":"2025-02-27T21:07:06.8620162Z","level":"INFO","msg":"sender: started","stream_id":"40127l2p"}
{"time":"2025-02-27T21:07:06.8620162Z","level":"INFO","msg":"handler: started","stream_id":"40127l2p"}
{"time":"2025-02-27T21:07:07.1725105Z","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-02-27T21:08:32.7704066Z","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/intenzia/lm-eval-harness-integration/40127l2p/file_stream\": EOF"}
{"time":"2025-02-27T21:10:56.2296959Z","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/intenzia/lm-eval-harness-integration/40127l2p/file_stream\": unexpected EOF"}
{"time":"2025-02-27T21:10:59.0126296Z","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.0.22:56384->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-27T21:48:49.5170244Z","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/intenzia/lm-eval-harness-integration/40127l2p/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
